title: Ralph Hightower — End Of Life Instructions
author:
  name: Ralph Hightower 
  email: ralph.hightower@gmail.com
  street_address: 1728 Old Lexington Hwy.
  city: Chapin
  state: "South Carolina"
  zip_code: 29036-9765
  country: United States of America
  phone: +1 (803) 622-6566
  #cellphone: ${{secrets.CELLPHONE}}
  #birthdate: ${{secrets.BIRTHDATE}}
  usage: The information in my EOL Instructions is reserved for my wife and attorney. 
description: > # this means to ignore newlines until "show_excerpts:"
  End Of Life Instructions for Paula and executor. Includes Obituary, Songs For Service, what to do with power tools, outdoor power tools, 
  camera gear, computers. 

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %I:%M:%S.%L %p %Z" # "%b %-d, %Y"

  # generate social links in footer
    social_links:
     - { platform: devto,          user_url: "https://dev.to/RalphHightower"}
  #   - { platform: dribbble,       user_url: "https://dribbble.com/RalphHightower" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/ralph.hightower" }
     - { platform: flickr,         user_url: "https://www.flickr.com/photos/RalphHightower" }
     - { platform: github,         user_url: "https://github.com/RalphHightower" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/RalphHightower" }
  #   - { platform: keybase,        user_url: "https://keybase.io/RalphHightower" }
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/RalphHightower" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/RalphHightower" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/RalphHightower" }
     - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/19978043/ralph-hightower" }
  #   - { platform: telegram,       user_url: "https://t.me/RalphHightower" }
  #   - { platform: twitter,        user_url: "https://twitter.com/RalphHightower" }
     - { platform: youtube,        user_url: "https://www.youtube.com/@RalphHightower" }


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
#
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
