version: '2'

services:

  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    container_name: resume-make
    entrypoint: /entrypoint.sh
    image: resume-make
    volumes:
      - .:/home/app/resume:z
