version: '2'

services:

  pandoc-make:
    build:
      context: .
      dockerfile: ./.docker/pandic.dockerfile
    container_name: pandoc-make
    entrypoint: /entrypoint.sh
    image: pandoc-make
    volumes:
      - .:/home/app/pandoc:z
