version: '2'

services:

  pandoc-make:
    build:
      context: .
      dockerfile: ./.docker/pandoc.dockerfile
    container_name: pandoc-make
    entrypoint: ./actions/entrypoint.sh
    image: pandoc-make
    volumes:
      - .:/home/app/pandoc:z
