name: Convert markdown to Word (Accounts)
on:
  push:
    branches:
       ["main"]
  pull_request:
    branches:
       ["main"]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          #node-version: 'node16'
          ref: ${{ github.event.push.head.ref }}
      - uses: docker://pandoc/core:3.1.1
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=Accounts.docx
            Accounts.md
      - name: ⤴ Commit updated version
        run: |
          git pull 'https://${{secrets.GITHUB_TOKEN}}@github.com/RalphHightower/EOL-RalphHightower.git'
          git config remote.origin.url 'https://${{secrets.GITHUB_TOKEN}}@github.com/RalphHightower/EOL-RalphHightower.git'
          git config user.name RalphHightower 
          git config user.email ralph.hightower@gmail.com
          git add .
          git commit -am "Update Document for Accounts"
          git push
