# This is a basic workflow to help you get started with Actions

name: build-resume

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'markdown/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Test directory contents
        run: 'ls -al'

      - name: Build resume
        uses: ./actions

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: Resume PDF # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: output/*.pdf

