name: Convert markdown to Word (Obituary)
on:
  push:
    branches:
      ["main"]
  pull_request:
    branches:
      ["main"]
jobs:
  convert_via_pandoc:
    env:
      birthdate: ${{ secrets BIRTHDATE }}
      cellphone: ${{ secrets.CELLPHONE }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          #node-version: 'node16'
          ref: ${{ github.event.push.head.ref }}
          #node-version: 'node16'
      - uses: docker://pandoc/core:2.19.2
        with:
          args: >- # allows you to break string into multiple lines
            cellphone: ${{secrets.CELL_PHONE}}
            birthdate: ${{secrets.BIRTH_DATE}}
            --standalone
            --output=Obituary.docx
            Obituary.md
      - name: ⤴ Commit updated version
        run: |
          env:
            cellphone: ${{secrets.CELLPHONE}}
            birthdate: ${{secrets.BIRTHDATE}}
          git pull 'https://${{secrets.GITHUB_TOKEN}}@github.com/RalphHightower/EOL-RalphHightower.git'
          git config remote.origin.url 'https://${{secrets.GITHUB_TOKEN}}@github.com/RalphHightower/EOL-RalphHightower.git'
          git config user.name RalphHightower 
          git config user.email ralph.hightower@gmail.com
          git add .
          git commit -am "Update Document for Obituary"
          git push
     
#######
