name: Convert markdown to Word (Obituary)
on:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.ref }}
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=Obituary.docx
            Obituary.md
      - name: ⤴ Commit updated version
        run: |
          git config remote.origin.url 'https://${{secrets.GITHUB_TOKEN}}@github.com/RalphHightower/EOL-RalphHightower-Obituary.git'
          git config user.name RalphHightower 
          git config user.email ralph.hightower@gmail.com
          git add .
          git commit -am "update Obituary"
          git push
     
