name: pandoc.yml – Create documents

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Pandoc
      run: |
        sudo apt-get install -y pandoc context

    - name: Initialize directories
      run: mkdir -p output

    - name: Check Pandoc version
      id: version
      run: |
        PANDOC_VERSION=$(pandoc --version | head -1 | cut -d' ' -f2 | cut -d'.' -f1)
        if [ "$PANDOC_VERSION" -eq "2" ]; then
          echo "::set-output name=smart_flag;-smart"
        else
          echo "::set-output name=smart_flag;--smart"
        fi

    - name: Build PDF
      run: |
        for f in markdown/*.md; do
          echo $f # debug
          FILE_NAME=$(basename "$f" | sed 's/.md//g')
          echo $FILE_NAME # debug
          echo output/${FILE_NAME}.pdf # debug 
          # pandoc --standalone \ # --template styles/chmduquesne.tex \
          #   --from markdown --to context \
          #  --variable papersize=letter \
          #   --verbose \ # debug
          #   --output output/${FILE_NAME}.tex $f
          # mtxrun --path=output --result=${FILE_NAME}.pdf --script context ${FILE_NAME}.tex
          pandoc --standalone --from markdown --to pdfa --output output/${FILE_NAME}.pdf $f
          git add output/${FILE_NAME}.pdf
        done

    - name: Build DOCX
      run: |
        for f in markdown/*.md; do
          FILE_NAME=$(basename "$f" | sed 's/.md//g')
          pandoc --standalone ${{ steps.version.outputs.smart_flag }} $f --output output/${FILE_NAME}.docx
          git add output/${FILE_NAME}.docx
        done

    - name: Check in documents 
      run : |
        git commit -m "[docs](doc): adding output to GitHub"

    - name: Upload output
      uses: actions/upload-artifact@v4.5.0
      with:
        name: output
        path: output
