# Sample workflow to run the action
name: permission_advisor.yml — Permissions Advisor

permissions:
  actions: read

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the workflow file to analyze'
        required: true
        type: string
      count:
        description: 'How many last runs to analyze'
        required: false
        type: number
        default: 10

jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: GitHubSecurityLab/actions-permissions/advisor@babd69bc8d78e6cdece903dfdcfb72d4e1a4f00d # v1.0.2-beta5
      with:
        name: ${{ inputs.name }}
        count: ${{ inputs.count }}
