name: stale-branches.yml – Delete Stale Branches

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  schedule:
    - cron: '0 6 * * 0'

permissions: 
  contents: read

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Stale Branches
        uses: crs-k/stale-branches@e876b957ab08f0bad43c8cc271a22cdd7604bd09 # v9.0.1
        with:
            # days-before-delete: 180
            # comment-updates: false
            # max-issues: 20
            tag-committer: true
            stale-branch-label: 'stale branch 🗑️'
            # compare-branches: 'info'
            # branches-filter-regex: '^((?!dependabot))'
            # rate-limit: false
            # pr-check: false
            # dry-run: false
            # ignore-issue-interaction: false
            # include-protected-branches: false
            # include-ruleset-branches: false
            # ignore-commit-messages: ''
            # ignore-committers: ''
