name: Convert markdown to Word
on: push

jobs:
  temp_conversion_via_pandoc:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:latest
        with:
          args: >- # allows you to break string into multiple lines
              for file in Obituary EquipmentDistrbution Assets Accounts ComputerSettings NetworkSettings
              do:
                  --standalone
                  --output=$file.docx
                  $file.md
                - uses: actions/upload-artifact@master
                with:
                name: $file.docx
                path: $file.docx
              endfor
