name: Convert markdown to Word
on: push

jobs:
  temp_conversion_via_pandoc:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
          for md in Obituary EquipmentDistrbution Assets Accounts ComputerSettings NetworkSettings
          do
            --standalone
            --output=$md.docx
            $md.md
            done
      - uses: actions/upload-artifact@master
        with:
            for md in Obituary EquipmentDistrbution Assets Accounts ComputerSettings NetworkSettings
            do
                name: $md.docx
                path: $md.docx
            done
