name: TheWorks - Converts multiple markdowns to Word (TheWorks.yml)
on:
    push:
      branches:
        - main
jobs:
  theworks_via_pandoc:
    runs-on: ubuntu-latest
     $for $(file) in $Obituary$, $Accounts$, $Assets$, $ComputerSettings$, $EquipmentDistrbution$, $SongsForService$
    #do;
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.ref }}
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=$file.docx
            $file.md
      - name: ⤴ Commit updated version
         $endfor
         done
        run: |
          git config remote.origin.url 'https://${{secrets.GITHUB_TOKEN}}@github.com/RalphHightower/EOL-RalphHightower.git'
          git config user.name RalphHightower 
          git config user.email ralph.hightower@gmail.com
          git add .
          git commit -am "update word"
          git push 
